name: Build EXE for UploadTool

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean package -e -X
      env:
        MAVEN_OPTS: "-Dfile.encoding=UTF-8"

    - name: Check generated JAR files
      run: |
       if (!(Test-Path "target/UploadTool-1.0-SNAPSHOT-shaded.jar")) {
        Write-Error "JAR file not found!"
        } else {
        dir target/
        }

    - name: Create EXE using jpackage
      run: |
       jpackage --input ./target/ \
       --name UploadTool \
       --main-jar UploadTool-1.0-SNAPSHOT-shaded.jar \
       --main-class org.example.Main \
       --type exe \
       --dest src/main/

    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: upload-tool-exe
        path: src/main/*.exe
